require 'rubygems'
require 'arduino_firmata'
require 'serialport'
require 'websocket-eventmachine-server'
require 'pp'
require 'osc'

$LOAD_PATH << '.'
require 'arduino'
require 'osc_class'
require 'pin'
require 'motor'
require 'hareket'
require 'log'
require 'sensor'